### ISSUE TITLE
Encountered device issue when running it 

### ISSUE THREAD

**Issue by wd255** [camenduru/videocomposer-colab#2]
Hi, I'm running this in google colab with A100 GPU, getting the following issue. 

[2023-09-19 00:30:12,741] INFO: GPU Memory used 12.70 GB
Traceback (most recent call last):
  File "/content/videocomposer/run_net.py", line 36, in <module>
    main()
  File "/content/videocomposer/run_net.py", line 31, in main
    inference_single(cfg.cfg_dict)
  File "/content/videocomposer/tools/videocomposer/inference_single.py", line 351, in inference_single
    worker(0, cfg)
  File "/content/videocomposer/tools/videocomposer/inference_single.py", line 695, in worker
    video_output = diffusion.ddim_sample_loop(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/videocomposer/artist/ops/diffusion.py", line 236, in ddim_sample_loop
    xt, _ = self.ddim_sample(xt, t, model, model_kwargs, clamp, percentile, condition_fn, guide_scale, ddim_timesteps, eta)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/videocomposer/artist/ops/diffusion.py", line 200, in ddim_sample
    _, _, _, x0 = self.p_mean_variance(xt, t, model, model_kwargs, clamp, percentile, guide_scale)
  File "/content/videocomposer/artist/ops/diffusion.py", line 166, in p_mean_variance
    var = _i(self.posterior_variance, t, xt)
  File "/content/videocomposer/artist/ops/diffusion.py", line 13, in _i
    return tensor[t].view(shape).to(x)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

I suspect its an error in t he run_net.py (probably some tensors not on gpu), but still pose here in case anyone came across it before.

**Comment by wd255** [comment]
Ok it's actually resolved here: https://github.com/damo-vilab/videocomposer/issues/9
